[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
user=root

[program:mariadb]
command=/usr/sbin/mysqld --user=mysql --socket=/var/run/mysqld/mysqld.sock --bind-address=127.0.0.1 --port=3306
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
priority=20
environment=APACHE_RUN_USER="www-data",APACHE_RUN_GROUP="www-data",APACHE_LOG_DIR="/var/log/apache2",APACHE_LOCK_DIR="/var/lock/apache2",APACHE_PID_FILE="/var/run/apache2/apache2.pid"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
